version: '3'

services:
  nuxt:
    build: ./client
    ports:
      - "4200:4200"
    env_file:
      - '.env'
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - front-tier

  express:
    build: ./server
    # command: nodemon --debug server.js
    ports:
      - "4000:4000"
    env_file:
      - '.env'
    networks:
      - back-tier

#   db:
#     image: mongo:9.4
#     container_name: db
#     volumes:
#       - "db-data:/var/lib/mongo/data"
#     networks:
#       - back-tier

# volumes:
#   db-data:

networks:
  front-tier:
  back-tier: