version: '3'

services:
  nuxt:
    build: ./client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/home/app/nuxt
      - /home/app/nuxt/node_modules

  express:
    build: ./server
    # command: nodemon --debug server.js
    ports:
      - "4000:4000"

#   db:
#     image: postgres:9.4
#     container_name: db
#     volumes:
#       - "db-data:/var/lib/postgresql/data"
#     networks:
#       - back-tier

# volumes:
#   db-data:

# networks:
#   front-tier:
#   back-tier: