version: '3'

services:
  # client:
  #   build: ./client
  #   ports:
  #     - "4200:4200"
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=4200
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   networks:
  #     - front-tier

  api:
    build: ./api
    # command: nodemon --debug server.js
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
       - ./api:/app
       - /app/node_modules
    networks:
      - back-tier

#   db:
#     image: mongo:3.0
#     container_name: db
#     volumes:
#       - "db-data:/var/lib/mongo/data"
#     networks:
#       - back-tier

# volumes:
#   db-data:

networks:
  # front-tier:
  back-tier: