version: '3'

services:
  nuxt:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  express:
    build: ./server
    # command: nodemon --debug server.js
    ports:
      - "4000:80"

#   db:
#     image: postgres:9.4
#     container_name: db
#     volumes:
#       - "db-data:/var/lib/postgresql/data"
#     networks:
#       - back-tier

# volumes:
#   db-data:

# networks:
#   front-tier:
#   back-tier: