version: '3'

services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    environment:
      - HOST=0.0.0.0
      - PORT=4200
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    build: ./api
    # command: nodemon --debug server.js
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
       - ./api:/app
       - /app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    # networks:
    #   - back-tier

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    # network_mode: "host"
    # networks:
    #   - back-tier

# volumes:
#   db-data:

# networks:
#   back-tier: